version: 0.0
os: windows
files:
  - source: ussd.jar
    destination: C:\deployments\ussd\

hooks:
  BeforeInstall:
    - location: BeforeInstall.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: AfterInstall.ps1
      timeout: 300
      runas: Administrator
  ApplicationStart:
    - location: ConfigureJava.ps1
      timeout: 300
      runas: Administrator
    - location: ApplicationStart.ps1
      timeout: 300
      runas: Administrator
  ValidateService:
    - location: ValidateService.ps1
      timeout: 300
      runas: Administrator
