version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - mvn clean package -DskipTests
      - ls -alR
      - mkdir -p scripts
      - cp scripts/* target/
      - cp appspec.yml target/
  post_build:
    commands:
      - echo Build completed on ` files
