version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/ussd.jar
  discard-paths: yes
  base-directory: target
